---
on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make deps app dialyze eunit
